### ISSUE TITLE
osf_upload() doesn't work as expected

### ISSUE THREAD

**Issue by davidrast3** [CenterForOpenScience/osfr#92] opened 2019-02-01 17:31 UTC
I noticed two issues when using 'osf_upload'

1) I cannot use file paths, as stated in the 'osft_upload' documentation. Instead, the file being uploaded must be in the current working directory otherwise I receive this message: "Error: Can't find file:
 DATA_FILE.CSV". I've tried uploading all sorts of file extensions but the upload is only successful if the file being uploaded is in the working directory. This makes using relative paths difficult, and therefore reduces reproducibility.  To get around this I am using the 'here' package to make relative paths feasible (e.g., "setwd(here::here("/data"))") but this can be confusing for people I share my scripts with and I am opposed to changing the working directory. 

2) 'osf_upload' does not work if a node is specified without it being saved as an object first. For instance, this command does not work:

osf_upload("randon_node",
           path = "data_file.csv",
           overwrite = TRUE)

Instead, an extra command is required for this work. Specifically, the node has to be saved as an object:

desired_osf_node <- osf_retrieve_node("random_node")
osf_upload(desired_osf_node,
           path = "data_file.csv",
           overwrite = TRUE)

I understand an osf_tbl is required for most 'osfr' functions. But, this isn't intuitive or logical for the end user. Can the function be rewritten such that if the user specifies a node directly, then the function can interpret or translate this as an osf_tbl? This would save a step and make the function easier to use and understand. Also, the changelog says this was done to make 'osfr' more similar to 'googledrive' but the latter package allows to specify folders or files by ID without any requirement to save either as a tbl.

**Comment by aaronwolen** [comment] 2019-02-01 18:48
Thanks for the feedback. 

1. I'm able to upload files outside of my current working directory without issue. Could you provide a reproducible example where that fails? 
2. I agree specifying the node ID directly would be more convenient—it's definitely on the list of things we'd like to add in the near future.

**Comment by davidrast3** [comment] 2019-02-01 18:53
1) Sure. But, I'm not sure how to do this without creating an OSF project and giving you read/write access to it. Do you have an alternative suggestion to achieve this?

2) thanks for the update.

**Comment by aaronwolen** [comment] 2019-02-01 19:06
Here's a quick example that worked for me. 

```r
library(osfr)
proj <- osf_create_project("Upload Test")

osf_upload(proj, system.file("DESCRIPTION", package = "osfr"))
```

Check the result here: <https://osf.io/wb3ze/>

**Comment by davidrast3** [comment] 2019-02-02 01:49
Tried to reproduce this first issue but this evening the script (without any changes) is running as expected. We spent about an hour troubleshooting this yesterday to no avail without changing the working directory. Not sure why it is suddenly working.

**Comment by aaronwolen** [comment] 2019-03-10 22:33
Closing this because the original issue was resolved. Feel free to re-open or file a new issue.

**Closed by aaronwolen** 2019-03-10 22:33 UTC
