### ISSUE TITLE
can't download an entire folder

### ISSUE THREAD

**Issue by bnicenboim** [CenterForOpenScience/osfr#86] opened 2019-01-23 08:53 UTC
I'm trying to download the entire folder "EEG data, before averaging/target determiner" from https://osf.io/ptqwm/

I thought that something like this would work:

```
 osf_retrieve_node("ptqwm")     %>%
    osf_ls_files %>%
    filter(name == "EEG data, before averaging") %>%
    pull(id) %>%
    osf_retrieve_node() %>%
    osf_ls_files %>%
    filter(name == "target determiner") %>%
    pull(id) %>%
    osf_retrieve_file()
```
but I can't list the files inside the folder `EEG data, before averaging`, the second osf_retrieve_node fails. What's the right way? And as a feature request, it would be nice if I could indicate an internal folder more directly (given that I know the folder structure).

BTW thanks for the awesome package!

**Comment by aaronwolen** [comment] 2019-01-23 14:20
Thanks! 

I noticed a couple issues with your example.

The `osf_retrieve_*()` functions are only needed initially to create an `osf_tbl` representation of something based on its GUID (a project in this case). 

``` r
project <- osf_retrieve_node("ptqwm")
```

Once you have that `osf_tbl` object it can be passed directly to any other osfr function—no need to `pull()` out the GUID and re-retrieve. 

Also, `osf_ls_files()` has a path argument that allows you to specify an internal directory:

``` r
osf_ls_files(project, path = "EEG data, before averaging/target determiner")
#> # A tibble: 10 x 3
#>    name                         id                       meta      
#>    <chr>                        <chr>                    <list>    
#>  1 s165_determiner_filtered.mat 5b2a5025c0f9b9000e2a0ef2 <list [3]>
#>  2 s168_determiner_filtered.mat 5b2a5025f11af8000e12acc3 <list [3]>
#>  3 s170_determiner_filtered.mat 5b2a5026c0f9b900102a0d52 <list [3]>
#>  4 s166_determiner_filtered.mat 5b2a5026f11af8000e12acc7 <list [3]>
#>  5 s169_determiner_filtered.mat 5b2a5026f11af8000d12b476 <list [3]>
#>  6 s164_determiner_filtered.mat 5b2a502bc0f9b9000f2a0e57 <list [3]>
#>  7 s160_determiner_filtered.mat 5b2a502bc0f9b900102a0d5a <list [3]>
#>  8 s159_determiner_filtered.mat 5b2a502bf11af8001012ab52 <list [3]>
#>  9 s161_determiner_filtered.mat 5b2a502df11af8001012ab58 <list [3]>
#> 10 s158_determiner_filtered.mat 5b2a502dc0f9b9000f2a0e5d <list [3]>
```

Let me know if that makes sense or if anything else is unclear.

**Comment by CEBerndsen** [comment] 2019-01-23 21:38
I tried something similar and was unable to download both the folder as a .zip or the individual files. 

For the individual files I tried:

    project %>%  
    osf_ls_files() %>% 
    filter(name == "Raw Data") %>% 
    osf_ls_files() %>% 
    filter(name == "fasta_data") %>% 
    osf_ls_files() %>% 
    filter(name == "unannotated") %>% 
    osf_ls_files(., n_max = 300) %>%
    osf_download()

The error I get is:

`This is not a vectorized function. Only the first row of 258 will be used. `

**Comment by bnicenboim** [comment] 2019-01-24 08:14
yeah, I still can't with:

```
 osf_retrieve_node("ptqwm") %>%
        osf_ls_files(path = "EEG data, before averaging/target determiner") %>%
        osf_download(path = eeg_kf_folder)
```
I'm having the same error as @CEBerndsen.

By the way, it's slightly confusing that path in `ls_files` is the remote path but path in `download` is the local file name or path.

**Comment by bnicenboim** [comment] 2019-01-24 09:01
> yeah, I still can't with:
> 
> ```
>  osf_retrieve_node("ptqwm") %>%
>         osf_ls_files(path = "EEG data, before averaging/target determiner") %>%
>         osf_download(path = eeg_kf_folder)
> ```
> 
> I'm having the same error as @CEBerndsen.
> 
> By the way, it's slightly confusing that path in `ls_files` is the remote path but path in `download` is the local file name or path.
Continuing the last thought, the tibble shown after downloading has a column called local_path, it might make sense that the argument would have the same name.

**Comment by aaronwolen** [comment] 2019-01-24 13:04
Sorry, @bnicenboim. I overlooked the *downloading* part of your question. The example I provided above just demonstrated how you can directly list the contents of a nested directory.

The message that you and @CEBerndsen received is just a warning to remind users that `osf_download()` is designed to handle a single input (i.e., an `osf_tbl_file` containing 1 row corresponding to a file or directory). In your example

```r
osf_retrieve_node("ptqwm") %>%
    osf_ls_files(path = "EEG data, before averaging/target determiner") %>%
    osf_download()
```

the output of `osf_ls_files()` contains multiple files, which triggers the warning to let you know only the first file will be downloaded. 

If you feel like `osf_download()` _should_ be able to handle multiple files—I'm right there with you. It's something I'm actively thinking about but there are few issues that need to be solved beforehand. 

Fortunately, you can still download the parent directory as a zip file

```r
 osf_retrieve_node("ptqwm") %>%
    osf_ls_files("EEG data, before averaging", pattern = "target determiner") %>%
    osf_download()
```

In this case, I'm using the pattern argument to directly filter for the *target determiner* directory, so the output passed to `osf_download()` is an `osf_tbl_file` with a single row.

---

@CEBerndsen, this strategy should work for you as well but I can't test directly without access to the referenced project.

**Comment by bnicenboim** [comment] 2019-01-24 13:33
Ok, great, now I understood how it is supposed to work.  I could download the entire folder using split/lapply:

```
osf_retrieve_node("ptqwm") %>%
    osf_ls_files(path = "EEG data, before averaging/target determiner") %>%
	split(1:nrow(x)) %>% 
		lapply(osf_download)
```

**Comment by bnicenboim** [comment] 2019-01-24 13:39
BTW, once in a while I start getting `Error in curl::curl_fetch_disk(x$url$url, x$disk, handle = x$url$handle) : 
  Error in the HTTP2 framing layer`  until I restart the R session

**Comment by aaronwolen** [comment] 2019-01-24 14:02
Possibly related to this https://github.com/curl/curl/issues/1587?

I haven't encountered that error personally but if you come up with a reproducible example please open a new issue so we can troubleshoot there.

**Comment by bnicenboim** [comment] 2019-01-25 14:22
> Ok, great, now I understood how it is supposed to work. I could download the entire folder using split/lapply:
> 
> ```
> osf_retrieve_node("ptqwm") %>%
>     osf_ls_files(path = "EEG data, before averaging/target determiner") %>%
> 	split(1:nrow(x)) %>% 
> 		lapply(osf_download)
> ```

just in case someone copypastes, it should be
```
osf_retrieve_node("ptqwm") %>%
    osf_ls_files(path = "EEG data, before averaging/target determiner") %>%
	{split(.,1:nrow(.))} %>% 
		lapply(osf_download)
```

**Comment by aaronwolen** [comment] 2019-01-25 14:35
Thanks for sharing. I'm considering implementing a general apply-like function for `osf_tbl`s in a future release to address these scenarios.

I'm going to close this since we resolved the downloading directories issue but feel free to reopen or submit a new issue if there are additional questions.

**Closed by aaronwolen** 2019-01-25 14:35 UTC
